# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shoppingmall # 자신의 환경에 맞게 변경 가능

    username: root # 자신의 환경에 맞게 변경 가능
    password: 1234 # 자신의 환경에 맞게 변경 가능

  mvc:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations: classpath:/static/images/
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  jackson:
    default-property-inclusion: non_null # DTO에서 null 값인 필드 전송 안됨

  # spring data jpa 설정
  jpa:
    hibernate:
      ddl-auto: update # create 처음 실행시 sql 테이블 생성 이후에는 none 으로 설정
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false

    jackson:
      default-property-inclusion: non_null

  #-------------------------------- jwt 설정 ---------------------------------------------------
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb


# 스프링 시큐리티 디버그 모드 활성화
logging:
  level:
    org.springframework.security: DEBUG

naver:
  client-id: 9Q8c9IK6So2HtQXhhMIS
  client-secret: ZFnuZ3iXqe
  redirect-uri: http://localhost:8080/login/oauth2/code/naver
google:
  client-id: 9Q8c9IK6So2HtQXhhMIS
  client-secret: ZFnuZ3iXqe
  redirect-uri: http://localhost:8080/login/oauth2/code/naver
kakao:
  native-key : d9d6789c8ec6218acc5e4cf93ea02643
  rest-key : 970cbe2ef7655253c4bdd40bbf7de07a
  js-key : 94cab928379892c46460d3a05dd6a444
  admin-key : d466614fd172f8683ca592784c75e8dc
  client-secret : OSmIl5qkDLlzMgRUIZLg8RtazwtaZp3E
  redirect-uri: http://localhost:8080/login/oauth2/code/kakao
